/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MMOTS_H_RPCGEN
#define _MMOTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TAILLEMOT 50
#define TAILLEDICTIONNAIRE 100

struct example {
	int exfield1;
	char exfield2;
};
typedef struct example example;

#define MMOTSPROG 0x30090949
#define MMOTSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INITIALISE 1
extern  int * initialise_1(CLIENT *);
extern  int * initialise_1_svc(struct svc_req *);
#define INSERTION 2
extern  int * insertion_1(char *, CLIENT *);
extern  int * insertion_1_svc(char *, struct svc_req *);
#define SUPPRESSION 3
extern  int * suppression_1(char *, CLIENT *);
extern  int * suppression_1_svc(char *, struct svc_req *);
#define CHERCHE 4
extern  int * cherche_1(char *, CLIENT *);
extern  int * cherche_1_svc(char *, struct svc_req *);
#define NBMOTS 5
extern  int * nbmots_1(CLIENT *);
extern  int * nbmots_1_svc(struct svc_req *);
extern int mmotsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INITIALISE 1
extern  int * initialise_1();
extern  int * initialise_1_svc();
#define INSERTION 2
extern  int * insertion_1();
extern  int * insertion_1_svc();
#define SUPPRESSION 3
extern  int * suppression_1();
extern  int * suppression_1_svc();
#define CHERCHE 4
extern  int * cherche_1();
extern  int * cherche_1_svc();
#define NBMOTS 5
extern  int * nbmots_1();
extern  int * nbmots_1_svc();
extern int mmotsprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_example (XDR *, example*);

#else /* K&R C */
extern bool_t xdr_example ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MMOTS_H_RPCGEN */
