/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INCREMENT_H_RPCGEN
#define _INCREMENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define INCRPROG 0x31234567
#define INCRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INCREMENT 1
extern  int * increment_1(int , CLIENT *);
extern  int * increment_1_svc(int , struct svc_req *);
extern int incrprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INCREMENT 1
extern  int * increment_1();
extern  int * increment_1_svc();
extern int incrprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INCREMENT_H_RPCGEN */
