/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mmots.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_initialise_1 (void  *argp, struct svc_req *rqstp)
{
	return (initialise_1_svc(rqstp));
}

static int *
_insertion_1 (char * *argp, struct svc_req *rqstp)
{
	return (insertion_1_svc(*argp, rqstp));
}

static int *
_suppression_1 (char * *argp, struct svc_req *rqstp)
{
	return (suppression_1_svc(*argp, rqstp));
}

static int *
_cherche_1 (char * *argp, struct svc_req *rqstp)
{
	return (cherche_1_svc(*argp, rqstp));
}

static int *
_nbmots_1 (void  *argp, struct svc_req *rqstp)
{
	return (nbmots_1_svc(rqstp));
}

static void
mmotsprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *insertion_1_arg;
		char *suppression_1_arg;
		char *cherche_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INITIALISE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _initialise_1;
		break;

	case INSERTION:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _insertion_1;
		break;

	case SUPPRESSION:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _suppression_1;
		break;

	case CHERCHE:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _cherche_1;
		break;

	case NBMOTS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _nbmots_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MMOTSPROG, MMOTSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MMOTSPROG, MMOTSVERS, mmotsprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MMOTSPROG, MMOTSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MMOTSPROG, MMOTSVERS, mmotsprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MMOTSPROG, MMOTSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
