/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int a;
	int b;
};
typedef struct operands operands;

struct op_result {
	int sum;
	int diff;
	int prod;
	double quot;
	int div_zero;
};
typedef struct op_result op_result;

#define CALCPROG 0x31234568
#define CALCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMPUTE 1
extern  op_result * compute_1(operands , CLIENT *);
extern  op_result * compute_1_svc(operands , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMPUTE 1
extern  op_result * compute_1();
extern  op_result * compute_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);
extern  bool_t xdr_op_result (XDR *, op_result*);

#else /* K&R C */
extern bool_t xdr_operands ();
extern bool_t xdr_op_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
