/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_op_result (XDR *xdrs, op_result *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diff))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->prod))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->sum);
		IXDR_PUT_LONG(buf, objp->diff);
		IXDR_PUT_LONG(buf, objp->prod);
		}
		 if (!xdr_double (xdrs, &objp->quot))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->div_zero))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sum))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->diff))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->prod))
				 return FALSE;

		} else {
		objp->sum = IXDR_GET_LONG(buf);
		objp->diff = IXDR_GET_LONG(buf);
		objp->prod = IXDR_GET_LONG(buf);
		}
		 if (!xdr_double (xdrs, &objp->quot))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->div_zero))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->sum))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diff))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prod))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->quot))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->div_zero))
		 return FALSE;
	return TRUE;
}
